node('master') {
    stage('trips') {
        git 'https://github.com/wsf11/DevOpsOHTeam2.git'
        dir("./apis/userprofile") {
            sh "docker build . -t ohdrteam02acr.azurecr.io/api-user/userprofile:1.0""
        }
    }
}

