
node('master') {
    stage('poi') {
        git 'https://github.com/wsf11/DevOpsOHTeam2.git'
        dir("./apis/poi/web") {
            sh "docker build . -t ohdrteam02acr.azurecr.io/api-poi/poi:1.0""
        }
    }
}

